name: Build Docker Extension for Kanvas

on:
  push:
    tags:
      - "v*"
    branches:
      - "master"
    paths-ignore:
      - "docs/**"
    #   - '.github/**'

jobs:
  extension-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout ğŸ›ï¸ repo
        uses: actions/checkout@v4

      - name: Build Extension UI
        run: |
          # Build UI. Produce local package.
          make ui-build

      - name: Build Extension
        run: |
            # Build service image to be deployed as a Docker extension
            make extension-build

      